name: '1919-backend'

services:
  bot:
    container_name: bot_back_dev
    image: bot_back_dev
    build:
       context: .
       dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      TOKEN: ${TOKEN}
      NGROC_TUNEL_URL: ${NGROC_TUNEL_URL}