name: '1919'

services:
  app:
    container_name: 1919_app-backend
    image: 1919_app-backend
    build:
       context: .
       dockerfile: Dockerfile
    command: fastapi run app/main.py --host 0.0.0.0
    expose:
      - 8000
    environment:
      TOKEN: ${TOKEN}
      NGROC_TUNEL_URL: ${NGROC_TUNEL_URL}
  postgres:
    container_name: 1919_postgres
    environment:
      POSTGRES_SERVER: "postgres"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:16.3
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

networks:
  default:
    name: "dolphin"
    external: true

volumes:
  postgres:
    name: 1919_postgres