name: '1919-backend'

services:
  app:
    container_name: 1919_app_back_dev
    image: 1919_app_back_dev
    build:
       context: .
       dockerfile: Dockerfile
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      TOKEN: ${TOKEN}
      NGROC_TUNEL_URL: ${NGROC_TUNEL_URL}
  postgres:
    container_name: 1919_postgres
    environment:
      POSTGRES_SERVER: "postgres"
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    image: postgres:16.3
    expose:
      - 5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
    name: 1919_postgres