name: '1919'

services:
  web:
    container_name: app-backend
    image: app-backend
    build:
       context: .
       dockerfile: Dockerfile
    command: fastapi run app/main.py --host 0.0.0.0
    expose:
      - 8000